sudo: required
services:
  - docker

before_install:
  - docker build -t simrangrewal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true simrangrewal/react-test npm run test

after_success:
  - docker build -t simrangrewal/multi-client ./client
  - docker build -t simrangrewal/multi-nginx ./nginx
  - docker build -t simrangrewal/multi-server ./server
  - docker build -t simrangrewal/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push simrangrewal/multi-client
  - docker push simrangrewal/multi-nginx
  - docker push simrangrewal/multi-server
  - docker push simrangrewal/multi-worker